name: graphql_schema3
version: 3.0.1
description: An implementation of GraphQL's type system in Dart. Basis of graphql_server3.
homepage: https://github.com/raphrmx/graphql_schema3
repository: https://github.com/raphrmx/graphql_schema3

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  collection: ^1.19.1
  meta: ^1.16.0
  source_span: ^1.10.1
  quiver: ^3.2.2

dev_dependencies:
  lints: ^6.0.0
